CREATE TABLE CUSTOM_QUERIES (
  ID          BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  NAME        varchar(50)   NOT NULL, 
  DESCRIPTION varchar(200), 
  QUERY_SQL   varchar(2000) NOT NULL)