-- http://db.apache.org/derby/docs/10.4/ref/
CREATE TABLE abp_STATE_NODE(
      NAME varchar(200),
     STATE_MACHINE_NODES_ID BIGINT,
  ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1))


 